ERROR - 2024-12-27 03:42:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in E:\htdocs\myproject\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 E:\htdocs\myproject\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_minimarket', 3306, '', 0)
#1 E:\htdocs\myproject\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\htdocs\myproject\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\htdocs\myproject\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\htdocs\myproject\app\Models\ModelSetting.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 E:\htdocs\myproject\vendor\myth\auth\src\Controllers\AuthController.php(415): App\Models\ModelSetting->DataWeb()
#6 E:\htdocs\myproject\vendor\myth\auth\src\Controllers\AuthController.php(60): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array)
#7 E:\htdocs\myproject\system\CodeIgniter.php(902): Myth\Auth\Controllers\AuthController->login()
#8 E:\htdocs\myproject\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 E:\htdocs\myproject\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\htdocs\myproject\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\htdocs\myproject\system\Commands\Server\rewrite.php(46): require_once('E:\\htdocs\\mypro...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in E:\htdocs\myproject\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 E:\htdocs\myproject\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\htdocs\myproject\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\htdocs\myproject\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\htdocs\myproject\app\Models\ModelSetting.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 E:\htdocs\myproject\vendor\myth\auth\src\Controllers\AuthController.php(415): App\Models\ModelSetting->DataWeb()
#5 E:\htdocs\myproject\vendor\myth\auth\src\Controllers\AuthController.php(60): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array)
#6 E:\htdocs\myproject\system\CodeIgniter.php(902): Myth\Auth\Controllers\AuthController->login()
#7 E:\htdocs\myproject\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 E:\htdocs\myproject\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\htdocs\myproject\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\htdocs\myproject\system\Commands\Server\rewrite.php(46): require_once('E:\\htdocs\\mypro...')
#11 {main}
CRITICAL - 2024-12-27 03:42:11 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_setting`
WHERE `id` = :id:', [...], false)
 3 APPPATH\Models\ModelSetting.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 VENDORPATH\myth\auth\src\Controllers\AuthController.php(415): App\Models\ModelSetting->DataWeb()
 5 VENDORPATH\myth\auth\src\Controllers\AuthController.php(60): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth\\login', [...])
 6 SYSTEMPATH\CodeIgniter.php(902): Myth\Auth\Controllers\AuthController->login()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2024-12-27 03:44:04 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in E:\htdocs\myproject\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 E:\htdocs\myproject\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_minimarket', 3306, '', 0)
#1 E:\htdocs\myproject\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\htdocs\myproject\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\htdocs\myproject\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\htdocs\myproject\app\Models\ModelSetting.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 E:\htdocs\myproject\vendor\myth\auth\src\Controllers\AuthController.php(415): App\Models\ModelSetting->DataWeb()
#6 E:\htdocs\myproject\vendor\myth\auth\src\Controllers\AuthController.php(60): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array)
#7 E:\htdocs\myproject\system\CodeIgniter.php(902): Myth\Auth\Controllers\AuthController->login()
#8 E:\htdocs\myproject\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 E:\htdocs\myproject\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\htdocs\myproject\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\htdocs\myproject\system\Commands\Server\rewrite.php(46): require_once('E:\\htdocs\\mypro...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in E:\htdocs\myproject\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 E:\htdocs\myproject\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\htdocs\myproject\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\htdocs\myproject\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\htdocs\myproject\app\Models\ModelSetting.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 E:\htdocs\myproject\vendor\myth\auth\src\Controllers\AuthController.php(415): App\Models\ModelSetting->DataWeb()
#5 E:\htdocs\myproject\vendor\myth\auth\src\Controllers\AuthController.php(60): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth...', Array)
#6 E:\htdocs\myproject\system\CodeIgniter.php(902): Myth\Auth\Controllers\AuthController->login()
#7 E:\htdocs\myproject\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#8 E:\htdocs\myproject\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\htdocs\myproject\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\htdocs\myproject\system\Commands\Server\rewrite.php(46): require_once('E:\\htdocs\\mypro...')
#11 {main}
CRITICAL - 2024-12-27 03:44:04 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_setting`
WHERE `id` = :id:', [...], false)
 3 APPPATH\Models\ModelSetting.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 VENDORPATH\myth\auth\src\Controllers\AuthController.php(415): App\Models\ModelSetting->DataWeb()
 5 VENDORPATH\myth\auth\src\Controllers\AuthController.php(60): Myth\Auth\Controllers\AuthController->_render('\\App\\Views\\auth\\login', [...])
 6 SYSTEMPATH\CodeIgniter.php(902): Myth\Auth\Controllers\AuthController->login()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
